spring:
  datasource:
    url: jdbc:mysql://localhost:3306/classmanager?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: ljd020624
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    #mybatis-plus
    mybatis-plus:
      mapper-locations: classpath:mapper/*AttendanceHistoryDao.xml
      global-config:
        db-config:
          field-strategy: not_empty
          id-type: auto
          db-type: mysql
        banner: false
    #热部署
    debug: true
    spring:
      devtools:
        restart:
          enabled: true  #设置开启热部署
          additional-paths: src/main/java
      theyleaf:
        cache: false    #页面不加载缓存，修改即时生效